### ISSUE TITLE
Update HTML FORM1.html

### ISSUE THREAD

**Issue by VENKATESH-USIRIKAYALA** [VENKATESH-USIRIKAYALA/web-page-repo#6]
Updated the heading.

**Comment by aneeshmaury** [comment]
![venktesh](https://github.com/VENKATESH-USIRIKAYALA/web-page-repo/assets/108884830/4f127098-3a69-44d0-b573-e54855ab8ba0)
![venkteshcode](https://github.com/VENKATESH-USIRIKAYALA/web-page-repo/assets/108884830/25d2e5d5-88db-48d5-8a11-04ed801eeca5)

Message :
1) There are methods for changing heading types.
2) also, you can change text or font style like you can do bold and italic and many more.
3) If you need to enhance the user interface then you can add a font family.

**Comment by aniruddha76** [comment]
assign this issue to me

**Comment by Mstanic05** [comment]
Assign this to me please!

**Comment by VENKATESH-USIRIKAYALA** [comment]
it was showing warning message I don't know why. can you tell me whether you are using public or private account. Mine is public.

**Comment by draunger** [comment]
Assign me

**Comment by VENKATESH-USIRIKAYALA** [comment]
it is completed

**Comment by aneeshmaury** [comment]
Hey brother
